import filterWindows from '../src/lib/filter-windows.js'
import { isKiwibankPageBoundary } from '../src/types/kiwibank-page-boundary'

const unchangedInputAndOutput = [
  '$1,512.64',
  '28 Mar',
  ' ',
  'POS W/D YUM RESTAURAN-13:01',
  ' ',
  '$9.50',
  ' ',
  '$1,503.14',
  '28 Mar',
  ' ',
  'POS W/D DANNY DOOLANS-13:24',
  ' ',
  '$22.90',
  ' ',
  '$1,480.24',
  '28 Mar',
  ' ',
  'POS W/D DANNY DOOLANS-13:26',
  ' ',
  '$12.30',
  ' ',
  '$1,467.94',
  '28 Mar',
  ' ',
  'POS W/D DANNY DOOLANS-13:29',
  ' ',
  '$4.40',
  ' ',
  '$1,463.54',
  '28 Mar',
  ' ',
  'POS W/D 359.45AUD @ 0.9251',
  'conversion rate',
  '$398.26',
  ' ',
  '$1,065.28',
  '28 Mar',
  ' ',
  '(INC. $9.72 CURRENCY CONVERSION',
  'COMMISSION) SP * HOUSE OF BLADES',
  'BOOLEAN GROVE',
  '28 Mar',
  ' ',
  'OLD WORLD OLDTOWN OLDTOWN',
  ' ',
  '$21.44',
  ' ',
  '$1,043.84',
  '28 Mar',
  ' ',
  'MEDITERRANEAN FOODS',
  'CLEVEDONIA',
  '$23.50',
  ' ',
  '$1,020.34',
  '29 Mar',
  ' ',
  'FROM G G K F SMYTHER',
  ' ',
  '$166.70',
  ' ',
  '$1,187.04',
  '29 Mar',
  ' ',
  'SP * SAN JOSE 171 CODA',
  'CLEVEDONIA',
  '$92.00',
  ' ',
  '$1,095.04',
  '29 Mar',
  ' ',
  'POS W/D COOLIO SWEETS-13:15',
  ' ',
  '$33.00',
  ' ',
  '$1,062.04',
  '29 Mar',
  ' ',
  'COUNTDOWN OLDTOWN',
  'CLEVEDONIA',
  '$4.00',
  ' ',
  '$1,058.04',
  '29 Mar',
  ' ',
  'X Bleeps St Clevedonia',
  ' ',
  '$113.94',
  ' ',
  '$944.10',
  '29 Mar',
  ' ',
  'X Bleeps St Clevedonia',
  ' ',
  '$9.70',
  ' ',
  '$934.40',
  '30 Mar',
  ' ',
  'PAY CRUMBLIES APPLIANCES',
]
describe('Window-filtering function', () => {
  test('passes innocent data through untouched', () => {
    expect(
      filterWindows(
        {
          windowSize: 13,
          predicate: (window: Array<string>) => !isKiwibankPageBoundary(window),
        },
        unchangedInputAndOutput
      )
    ).toEqual(unchangedInputAndOutput)
  })

  test('filters out the appropriate rows', () => {
    // NOTE: consider the following additional cases:
    // - input data with at least windowSize number of normal rows preceding the rows to filter
    // - input data with an interval SHORTER than windowSize between rows that should be filtered
    const inputRows = [
      '11 Apr',
      ' ',
      'POS W/D DANNY DOOLANS-12:44',
      ' ',
      '$4.50',
      ' ',
      '$3,436.52',
      'ST 8190 050718',
      'Page 7 of 8 (Please turn over)',
      '',
      'Date',
      ' ',
      'Transaction',
      ' ',
      'Withdrawals',
      ' ',
      'Deposits',
      ' ',
      'Balance',
      '',
      '11 Apr',
      ' ',
      'POS W/D DANNY DOOLANS-12:46',
      ' ',
      '$37.74',
      ' ',
      '$3,398.78',
      '11 Apr',
      ' ',
      'TRF 9988********6666',
      ' ',
      '$20.00',
      ' ',
      '$3,378.78',
    ]
    const expected = [
      '11 Apr',
      ' ',
      'POS W/D DANNY DOOLANS-12:44',
      ' ',
      '$4.50',
      ' ',
      '$3,436.52',
      '11 Apr',
      ' ',
      'POS W/D DANNY DOOLANS-12:46',
      ' ',
      '$37.74',
      ' ',
      '$3,398.78',
      '11 Apr',
      ' ',
      'TRF 9988********6666',
      ' ',
      '$20.00',
      ' ',
      '$3,378.78',
    ]
    expect(
      filterWindows(
        {
          windowSize: 13,
          predicate: (window: Array<string>) => !isKiwibankPageBoundary(window),
        },
        inputRows
      )
    ).toEqual(expected)
  })
})
